### ISSUE TITLE
Validate / Generate dependency section for README

### ISSUE THREAD

**Issue by jakobbraun** [exasol/release-robot#19] opened 2020-09-04 08:45 UTC
At the moment the dependency declarations in the readme are generated by hand. That leads to mistakes and consumes time.

It would be very helpful if RR would generate those declarations automatically during release.

For maven, the version can at least for some packages be extracted from their pom file.

**Comment by jakobbraun** [comment] 2020-09-04 12:03
For maven, this plugin looks promising http://maven.apache.org/plugins/maven-project-info-reports-plugin/

**Comment by AnastasiiaSergienko** [comment] 2020-09-10 06:51
I think RR won't edit the project files, it should be a separated tool to generate something like that because it won't really fit here

**Comment by AnastasiiaSergienko** [comment] 2020-09-14 11:24
This ticket is a duplicate of #4. I'll close it for now

**Closed by AnastasiiaSergienko** 2020-09-14 11:24 UTC
Labels: duplicate, feature
